### ISSUE TITLE
ido-ubiquitous seems to be causing formatting issues in Custom-mode buffers in emacsclient

### ISSUE THREAD

**Issue by ylluminarious** [DarwinAwardWinner/ido-ubiquitous#112] opened 2016-06-23 19:26 UTC
When I start an Emacs server and client from the shell like so:
```shell
Emacs --daemon && emacsclient -c&
```
I have an issue wherein the formatting in `Custom-mode` buffers is not correct. It looks like this:

![emacsclient_formatting_bug](https://cloud.githubusercontent.com/assets/4912973/16315323/d0a3f214-394f-11e6-8242-de1493eb402f.png)

However, when I comment out these lines from my `.emacs` file:
```emacs-lisp
(require 'ido-ubiquitous)
(ido-ubiquitous-mode t)
```
and start Emacs with the same invocation as above, `Custom-mode` buffers look as expected:

![emacsclient_formatting_correct](https://cloud.githubusercontent.com/assets/4912973/16316411/78914612-3954-11e6-8350-342dea55b3eb.png)

I don't have this issue when I create clients after starting the server with `M-x server-start`, so I suspect that it has something to do with me starting the daemon / server from the terminal. I'm not sure if `ido-ubiquitous` is the exact culprit, though, esp. since there are some other oddities in starting `emacsclient` from a terminal such as there being a `*` instead of `×` for the `smart-mode-line` package's "modified" character as well as some colors being slightly off in certain places. Such issues are not fixed when I comment out the aforementioned lines from my `.emacs` file.

Also, I'm running Emacs 25.1.50.2 on OS X 10.11.4.

**Comment by DarwinAwardWinner** [comment] 2016-06-27 23:31
I have not found daemon mode to be reliable in OS X. Here's what I use instead: https://github.com/DarwinAwardWinner/osx-pseudo-daemon

**Comment by ylluminarious** [comment] 2016-06-27 23:46
@DarwinAwardWinner Hey, thanks. That's actually rather cool. I think I'll use it on my OS X setup for the time being at least, but I'll leave this ticket open in case someone can solve the weirdness that's going on with a regular daemon on OS X.

**Comment by DarwinAwardWinner** [comment] 2016-06-27 23:55
I assume that these screenshots are from a GUI window created using emacsclient? If so, I have a guess as to what the problem is. If Emacs is not running with a GUI window, it can't draw fancy buttons and will fall back to indicating buttons using square brackets in the terminal, and it will be stuck with this fallback even after a GUI window is created later. ido-ubiquitous does some advanced tricks with the custom system that probably triggers early loading of the system for button drawing, thus triggering the bug. See if you can reproduce it by adding `(customize-variable 'ido-mode)` to your init file instead of loading ido-ubiquitous. This should theoretically trigger the same loading of the custom button code.

**Comment by ylluminarious** [comment] 2016-06-28 00:03
@DarwinAwardWinner Yes, you are correct that these screenshots are from a GUI window created with emacsclient. Re: your hypothesis about what the problem is -- Interesting, glad to have a better idea as to what's going on here. Also, you are correct in asserting that adding `(customize-variable 'ido-mode)` to my `.emacs` does trigger the bug.

**Comment by DarwinAwardWinner** [comment] 2016-06-28 00:11
Ok, I'm going to close this since its not a bug in ido-ubiquitous.

**Comment by ylluminarious** [comment] 2016-06-28 00:12
@DarwinAwardWinner Sure, np.

**Closed by DarwinAwardWinner** 2016-06-28 00:11 UTC
